### ISSUE TITLE
How to data to view on POST?

### ISSUE THREAD

**Issue by collinglass** [kennygrant/gohackernews#13]
Hi gents and ladies,

I'd like to add data to the story view when a user upvotes or downvotes. I'd like to know how one could implement this? Rather than discuss if it's suitable for this project.

Thanks,
Collin

**Comment by kennygrant** [comment]
Could be interesting. What sort of data did you want to add here? At present we just +/- the points and that is presented with the story. Do you mean data on who voted?

**Comment by kennygrant** [comment]
Closing as haven't heard back, but please reopen if you would like to request this with more detail.
