### ISSUE TITLE
Error: Could not render template

### ISSUE THREAD

**Issue by gnoirzox** [kennygrant/gohackernews#17]
Hi there,

I tried to set it up on my own but I am currently stuck on that bug on any view that should display a list of news.

>  Error:#error Could not render template stories/views/index.html.got - template: stories/views/row.html.got:2:19: executing "stories/views/row.html.got" at <.story.CanonicalURL>: can't evaluate field CanonicalURL in type interface {}

I can't figure out why this happens... Did you previously encounter that issue ?

Thanks,

gnoirzox

**Comment by kennygrant** [comment]
Cool, glad you worked it out. Any other problems/suggestions please file an issue.
