### ISSUE TITLE
Can't run using MySQL

### ISSUE THREAD

**Issue by ariestiyansyah** [kennygrant/gohackernews#20]
Can you share the schema if using mysql database?

appreciate it.

**Comment by kennygrant** [comment]
I've been using psql, it's been a while since I used mysql, however hopefully the sql supplied in https://github.com/kennygrant/gohackernews/blob/master/db/migrate/Create-Tables.sql.tmpl works for you? If not let me know what problem you see when executing it with mysql.

**Comment by kennygrant** [comment]
Closing as I think the scheme above should be enough (with the 2.0 migration as well), let me know if you see problems though.
