### ISSUE TITLE
WYSIWYG editor in stories/create on Firefox

### ISSUE THREAD

**Issue by simukti** [kennygrant/gohackernews#23]
I've seen recent changes to Golang News, overall is great, but there is one thing I just found out a little bit "annoying" for me, I use Firefox 52.0.2 on OSX and visit https://golangnews.com/stories/create ,WYSIWYG editor's text cursor looks like this (screenshot attached) :

![screen-shot-2017-04-14-at-15 36 03](https://cloud.githubusercontent.com/assets/183417/25038551/8fe25672-2129-11e7-81c9-bf7089430565.jpg)

This is only appear on Firefox, in Chrome (57.0.2987.133) everything's just fine.

**Comment by kennygrant** [comment]
Thanks will take a look
