### ISSUE TITLE
Errors in development environment 

### ISSUE THREAD

**Issue by gnoirzox** [kennygrant/gohackernews#27]
I am getting some weird errors when I am trying to access to the following routes:

> Not Found
   Sorry, the page you're looking for couldn't be found.
   File:gohackernews/src/app/handlers.go:37
   Error:stat ./public/users: no such file or directory
for http://localhost:3000/users/

> Not Allowed
  Sorry, I can't let you do that.
  File:src/stories/actions/create.go:27
  Error:can: no authorisation for action:2 stories/0 /0
for http://localhost:3000/stories/create

Also, I have empty parentheses displayed into the user_badge list in the header, the span class="long" is not displayed for some reason.

Do you know, by any chance, if this is due to the fact that I am not using a https connection in my local environment? It seems to be an issue with the cookie or the authentication but I cannot figure out why this is happening.

**Comment by kennygrant** [comment]
I don't think it is to do with lack of https locally, it is designed to run without https locally. 

The path which works is the path without a trailing slash (when logged in):

`http://localhost:3000/users`

I could I guess strip trailing slashes? Re empty parens, perhaps your username is blank? It does sound like a possible login issue. Do you have a session_name key in your secrets/fragmenta.json file (please don't post it all here obviously)? I ran into a problem with that not being created a while ago, if not there try adding this to the json:

`"session_name": "golang_news",`

**Comment by gnoirzox** [comment]
I have added the session_name into my fragmenta.json and I can see the named cookie in the developer tools now. 

I have also removed my test user from the users table but I am still getting the same issue. So, yes it does look like it is a login issue..

**Comment by gnoirzox** [comment]
Fixed issue. It was due to a bad merge..
