### ISSUE TITLE
illegal base64 data at input byte 3

### ISSUE THREAD

**Issue by spearous** [kennygrant/gohackernews#30]
I searched online for this but couldn't solve it for quite long. After I successfully see the front page, I try to register a new user. But after I click the button, it returns this error: illegal base64 data at input byte 3 (and the screen capture is attached):

![27958515-20dd732c-62e9-11e7-8547-6e6a2e2bc3ca](https://user-images.githubusercontent.com/12047203/28236035-fc12e3a8-68e0-11e7-9ecc-f0a8924fcb29.jpg)

Not sure what is happened? Thank you!

**Comment by kennygrant** [comment]
I'll look into it thanks

**Comment by kennygrant** [comment]
This is caused by a missing key in the secrets file, which was omitted from bootstrapping. You should be able to add a "session_name" key (with any text value "my_session" for example), and then it will work.  

I've improved error reporting so that it doesn't return such an inscrutable error.
