### ISSUE TITLE
unable to submit new storie

### ISSUE THREAD

**Issue by m7shapan** [kennygrant/gohackernews#37]
event though I have 3 points it gives me this message `You need to be registered and have more than 1 points to submit stories.`

**Comment by kennygrant** [comment]
I have to update this message, it should say 10 points - we had a problem with spammers and I had to make the rules stricter. I can upgrade your points though, send me an email.

**Comment by m7shapan** [comment]
@kennygrant Thanks bro, I will send you an email.
