### ISSUE TITLE
Mysql

### ISSUE THREAD

**Issue by pjebs** [kennygrant/gohackernews#38]
What changes would I need to do to make it work with MySQL?

**Comment by kennygrant** [comment]
You change the adapter for the db to be mysql when calling OpenDatabase (so change the db_adapter in secrets/fragmenta.json). I haven't documented stuff like that though as I haven't used mysql in quite a while, I tend to use postgresql nowadays.

**Comment by pjebs** [comment]
Do you think any of the queries may be problematic if run on mysql?

**Comment by kennygrant** [comment]
They shouldn't be no, they're pretty standard sql. The migration is the only area where I think I haven't supported mysql.

**Comment by pjebs** [comment]
It turns out that `rank` column must be wrapped in backticks with mysql8+
