### ISSUE TITLE
points question

### ISSUE THREAD

**Issue by pjebs** [kennygrant/gohackernews#44]
I tried to submit a story.
I can see in the db my user has 1 point.
You need at least 2 to submit.
How do I improve my points?

**Comment by kennygrant** [comment]
Add a comment, and get upvoted. If you link to a useful comment I can upvote it for you though. The restriction is to stop spam I'm afraid.

**Comment by pjebs** [comment]
Can't google recatcha be used instead?
A new user should be able to submit a link. @kennygrant
