### ISSUE TITLE
Unable to login to the site

### ISSUE THREAD

**Issue by ctd1500** [kennygrant/gohackernews#7]
I successfully registered an account, but I can't seem to login.
I've tried logging in with Chrome, Firefox, and even IE, all fail.  I even tried from my phone, figuring IPv6 might be the problem, but it failed as well.

The /users/login page returns a `Status Code: 302 Found` and then loads the home page, no errors or anything else unusual.

**Comment by kennygrant** [comment]
Thanks I'll have a look, that sounds weird.

**Comment by kennygrant** [comment]
This should now be fixed, please reopen if you still see problems logging in.
