### ISSUE TITLE
What did you deploy this on? 

### ISSUE THREAD

**Issue by timothybone** [kennygrant/gohackernews#9]
AWS? Heroku? GAE? 

Just curious, thank you!

**Comment by kennygrant** [comment]
Setup is listed at the foot of the page - it's just on a $5 DO instance, running Caddy Server in front for assets and certs (if you haven't tried caddy I'd recommend it). I did try out CoreOS but settled on Ubuntu for familiarity. I load tested for a few hundred concurrent connections and it started to slow down, but it's not getting that sort of traffic as yet. 

It should run fine on GAE, heroku etc too though.
